whitelist_rules:

# Exclude Pods and tests from linting
excluded:
  - fastlane
  - Pods
  - .build
  - workflows
  - BuildTools

line_length:
  error: 270
  warning: 250
  ignores_comments: true
  ignores_function_declarations: true

file_length:
  warning: 500

type_body_length:
  warning: 500

identifier_name:
  min_length: 2 # only min_length


# Rules which will be excluded from running
disabled_rules:
  - todo
  - implicitly_unwrapped_optional
  - trailing_closure

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - fatal_error_message
  - first_where
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_parameters
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - explicit_init
