name: BuildAndTestLinux

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Swift
      uses: YOCKOW/Action-setup-swift@master
    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install -y libxml2 libxml2-dev && mint install nicklockwood/SwiftFormat
    - name: Lint
      run: make lint
    - name: Build
      run: make build
    - name: Test
      run: make test
