name: BuildAndTestMacOS

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: brew install libxml2
    - name: Lint
      run: make lint
    - name: Build
      run: make build
    - name: Test
      run: make test
