name: BuildAndTest

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: libxml2
      run: brew install libxml2
    - name: Lint
      run: cd BuildTools && swift run -c release swiftformat --lint ../
    - name: Build
      run: swift build -Xcc -I/usr/local/opt/libxml2/include/libxml2
    - name: Run tests
      run: swift test -Xcc -I/usr/local/opt/libxml2/include/libxml2 -Xlinker -lxml2
